import type { AssetSchema } from "../types";
import { GLOBAL_INHERITED_RULES } from "../brand-rules";

export const emailTierTableSchema: AssetSchema = {
  id: "email-tier-table",
  displayName: "Email Sponsor Tier Table Block",
  category: "email",
  fluid: true,
  outputFormats: ["html"],
  inheritedRules: GLOBAL_INHERITED_RULES,
  notes:
    "Condensed 3-5 row table summarizing sponsor tiers — name + price + one-line key deliverable. Full tier matrix lives in the sponsor deck; this is the teaser.",
  fields: [
    {
      name: "section_kicker",
      label: "Section kicker",
      type: "text",
      minChars: 3,
      maxChars: 28,
      required: true,
      position: "kicker",
      tokenRole: "label_chip",
      example: "SPONSOR THE 7TH ANNUAL",
    },
    {
      name: "section_headline",
      label: "Section headline",
      type: "text",
      minChars: 8,
      maxChars: 60,
      required: true,
      position: "title",
      tokenRole: "display_small",
    },
    {
      name: "intro_line",
      label: "Intro line (1 sentence)",
      type: "text",
      minChars: 20,
      maxChars: 140,
      required: true,
      position: "intro",
      tokenRole: "body",
    },
    {
      name: "tier_names",
      label: "Tier names (ordered, highest tier first)",
      type: "list",
      required: true,
      position: "tier_name_column",
      tokenRole: "display_small",
      listItemMax: 28,
    },
    {
      name: "tier_prices",
      label: "Tier prices (parallel array — same order as tier_names)",
      type: "list",
      required: true,
      position: "tier_price_column",
      tokenRole: "stat_number",
      listItemMax: 16,
    },
    {
      name: "tier_hooks",
      label: "One-line deliverable per tier (parallel array)",
      type: "list",
      required: true,
      position: "tier_hook_column",
      tokenRole: "body_small",
      listItemMax: 80,
    },
    {
      name: "cta_label",
      label: "CTA button label",
      type: "text",
      minChars: 3,
      maxChars: 22,
      required: true,
      position: "cta_button",
      tokenRole: "label_chip",
      example: "VIEW SPONSOR DECK",
    },
    {
      name: "cta_url",
      label: "CTA URL",
      type: "url",
      required: true,
      position: "cta_meta",
    },
    {
      name: "deadline_line",
      label: "Deadline note",
      type: "text",
      minChars: 0,
      maxChars: 80,
      required: false,
      position: "deadline",
      tokenRole: "caption",
      example: "Tiers lock June 1, 2026.",
    },
  ],
  imageSlots: [],
};
