import type { AssetSchema } from "../types";
import { GLOBAL_INHERITED_RULES } from "../brand-rules";

export const emailHeroSchema: AssetSchema = {
  id: "email-hero",
  displayName: "Email Hero Block (HTML section)",
  category: "email",
  fluid: true,
  outputFormats: ["html"],
  inheritedRules: GLOBAL_INHERITED_RULES,
  fields: [
    {
      name: "audience_salutation",
      label: "Audience salutation",
      type: "text",
      minChars: 3,
      maxChars: 40,
      required: true,
      position: "top",
      tokenRole: "body_large",
      example: "Hi {{FIRSTNAME}}",
      rules: ["no_friends_salutation"],
    },
    {
      name: "hero_headline",
      label: "Hero headline",
      type: "text",
      minChars: 10,
      maxChars: 70,
      required: true,
      position: "hero_title",
      tokenRole: "display_large",
    },
    {
      name: "hero_deck",
      label: "Hero deck (2-3 sentences)",
      type: "richtext",
      minChars: 40,
      maxChars: 280,
      required: true,
      position: "hero_body",
      tokenRole: "body_large",
    },
    {
      name: "proof_stat",
      label: "Proof stat",
      type: "text",
      minChars: 3,
      maxChars: 50,
      required: false,
      position: "proof_block",
      tokenRole: "stat_number",
      rules: ["verified_stats_only"],
    },
    {
      name: "proof_caption",
      label: "Proof caption",
      type: "text",
      minChars: 0,
      maxChars: 80,
      required: false,
      position: "proof_block_caption",
      tokenRole: "caption",
    },
  ],
  imageSlots: [
    {
      name: "hero_image",
      role: "hero",
      widthPx: 600,
      heightPx: 360,
      required: false,
      approvedSource: "program_photo_pool",
    },
  ],
};
