import type { AssetSchema } from "../types";
import { GLOBAL_INHERITED_RULES } from "../brand-rules";

export const emailStatStripSchema: AssetSchema = {
  id: "email-stat-strip",
  displayName: "Email Stat Strip Block",
  category: "email",
  fluid: true,
  outputFormats: ["html"],
  inheritedRules: GLOBAL_INHERITED_RULES,
  notes:
    "3 or 4 big numbers in a horizontal row (stacks to vertical on mobile). Scale-proof block that sits just below the hero.",
  fields: [
    {
      name: "stat_1_number",
      label: "Stat 1 number",
      type: "text",
      minChars: 1,
      maxChars: 10,
      required: true,
      position: "col_1_number",
      tokenRole: "stat_number",
      rules: ["verified_stats_only"],
    },
    {
      name: "stat_1_label",
      label: "Stat 1 label",
      type: "text",
      minChars: 3,
      maxChars: 36,
      required: true,
      position: "col_1_label",
      tokenRole: "caption",
    },
    {
      name: "stat_2_number",
      label: "Stat 2 number",
      type: "text",
      minChars: 1,
      maxChars: 10,
      required: true,
      position: "col_2_number",
      tokenRole: "stat_number",
      rules: ["verified_stats_only"],
    },
    {
      name: "stat_2_label",
      label: "Stat 2 label",
      type: "text",
      minChars: 3,
      maxChars: 36,
      required: true,
      position: "col_2_label",
      tokenRole: "caption",
    },
    {
      name: "stat_3_number",
      label: "Stat 3 number",
      type: "text",
      minChars: 1,
      maxChars: 10,
      required: true,
      position: "col_3_number",
      tokenRole: "stat_number",
      rules: ["verified_stats_only"],
    },
    {
      name: "stat_3_label",
      label: "Stat 3 label",
      type: "text",
      minChars: 3,
      maxChars: 36,
      required: true,
      position: "col_3_label",
      tokenRole: "caption",
    },
    {
      name: "stat_4_number",
      label: "Stat 4 number (optional)",
      type: "text",
      minChars: 0,
      maxChars: 10,
      required: false,
      position: "col_4_number",
      tokenRole: "stat_number",
      rules: ["verified_stats_only"],
    },
    {
      name: "stat_4_label",
      label: "Stat 4 label (optional)",
      type: "text",
      minChars: 0,
      maxChars: 36,
      required: false,
      position: "col_4_label",
      tokenRole: "caption",
    },
  ],
  imageSlots: [],
};
