import type { AssetSchema } from "../types";
import { GLOBAL_INHERITED_RULES } from "../brand-rules";

export const emailEventDetailsSchema: AssetSchema = {
  id: "email-event-details",
  displayName: "Email Event Details Block",
  category: "email",
  fluid: true,
  outputFormats: ["html"],
  inheritedRules: GLOBAL_INHERITED_RULES,
  notes:
    "Anchor card that surfaces the what/when/where for the featured event. Gold block on white, or white-on-black variant.",
  fields: [
    {
      name: "kicker",
      label: "Kicker (eyebrow label)",
      type: "text",
      minChars: 3,
      maxChars: 28,
      required: true,
      position: "kicker",
      tokenRole: "label_chip",
      example: "FLAGSHIP EVENT · 2026",
    },
    {
      name: "event_name",
      label: "Event name",
      type: "text",
      minChars: 4,
      maxChars: 50,
      required: true,
      position: "title",
      tokenRole: "display_medium",
    },
    {
      name: "date_line",
      label: "Date line",
      type: "text",
      minChars: 6,
      maxChars: 40,
      required: true,
      position: "date",
      tokenRole: "body_large",
      example: "Saturday, August 1, 2026",
    },
    {
      name: "time_line",
      label: "Time line",
      type: "text",
      minChars: 3,
      maxChars: 30,
      required: true,
      position: "time",
      tokenRole: "body",
      example: "10 AM – 2 PM",
    },
    {
      name: "location_name",
      label: "Location name",
      type: "text",
      minChars: 3,
      maxChars: 50,
      required: true,
      position: "location_title",
      tokenRole: "body_large",
    },
    {
      name: "location_address",
      label: "Address",
      type: "text",
      minChars: 0,
      maxChars: 80,
      required: false,
      position: "location_secondary",
      tokenRole: "body_small",
    },
    {
      name: "add_to_calendar_url",
      label: "Add-to-calendar URL",
      type: "url",
      required: false,
      position: "meta",
    },
  ],
  imageSlots: [],
};
