import type { AssetSchema } from "../types";
import { GLOBAL_INHERITED_RULES } from "../brand-rules";

export const eventCardSchema: AssetSchema = {
  id: "event-card",
  displayName: "Event Card (web + social index)",
  category: "web",
  fluid: true,
  outputFormats: ["jsx"],
  inheritedRules: GLOBAL_INHERITED_RULES,
  notes:
    "Used on /events calendar and homepage. Chip row reflects signupFilters from Sanity event schema.",
  fields: [
    {
      name: "event_title",
      label: "Event title",
      type: "text",
      minChars: 4,
      maxChars: 50,
      required: true,
      position: "title",
      tokenRole: "display_small",
    },
    {
      name: "program_tag",
      label: "Program tag",
      type: "text",
      minChars: 3,
      maxChars: 22,
      required: true,
      position: "eyebrow",
      tokenRole: "label_chip",
    },
    {
      name: "event_date",
      label: "Event date",
      type: "text",
      minChars: 3,
      maxChars: 28,
      required: true,
      position: "date",
      tokenRole: "body",
    },
    {
      name: "event_location",
      label: "Event location",
      type: "text",
      minChars: 3,
      maxChars: 50,
      required: true,
      position: "location",
      tokenRole: "body_small",
    },
    {
      name: "short_description",
      label: "Short description (2 lines)",
      type: "text",
      minChars: 20,
      maxChars: 160,
      required: true,
      position: "body",
      tokenRole: "body_small",
    },
    {
      name: "signup_chips",
      label: "Signup filter chips",
      type: "list",
      required: false,
      position: "chip_row",
      tokenRole: "label_chip",
      enumValues: ["volunteer", "vendor", "attendee", "sponsor"],
      listItemMax: 12,
    },
    {
      name: "cta_label",
      label: "CTA label",
      type: "text",
      minChars: 3,
      maxChars: 22,
      required: true,
      position: "cta",
      tokenRole: "label_chip",
    },
    {
      name: "cta_url",
      label: "CTA URL",
      type: "url",
      required: true,
      position: "cta_meta",
    },
  ],
  imageSlots: [
    {
      name: "event_thumb",
      role: "proof_photo",
      widthPx: 800,
      heightPx: 500,
      required: false,
      approvedSource: "program_photo_pool",
    },
    {
      name: "program_icon",
      role: "icon",
      required: true,
      approvedSource: "program_icon_set",
      notes: "One of 7 program icons (fire, school, youth, beach, gift, wellness, food).",
    },
  ],
};
