import type { AssetSchema } from "../types";
import { GLOBAL_INHERITED_RULES } from "../brand-rules";

export const flyer11x17Schema: AssetSchema = {
  id: "flyer-11x17",
  displayName: "Flyer 11×17 (poster)",
  category: "print",
  widthPx: 3300,
  heightPx: 5100,
  outputFormats: ["pdf", "png"],
  inheritedRules: GLOBAL_INHERITED_RULES,
  notes:
    "Poster sibling of 8.5x11 flyer with longer headline runway and larger photo panel. Same field set, different proportions and character budgets.",
  fields: [
    {
      name: "program_tag",
      label: "Program tag / eyebrow",
      type: "text",
      minChars: 3,
      maxChars: 28,
      required: true,
      position: "top_bar",
      tokenRole: "label_chip",
    },
    {
      name: "headline",
      label: "Headline",
      type: "text",
      minChars: 8,
      maxChars: 55,
      required: true,
      position: "upper_hero",
      tokenRole: "display_xl",
    },
    {
      name: "deck",
      label: "Deck",
      type: "text",
      minChars: 10,
      maxChars: 140,
      required: true,
      position: "below_hero",
      tokenRole: "body_large",
    },
    {
      name: "event_date",
      label: "Event date",
      type: "text",
      minChars: 3,
      maxChars: 28,
      required: true,
      position: "date_block",
      tokenRole: "display_medium",
    },
    {
      name: "event_time",
      label: "Event time",
      type: "text",
      minChars: 3,
      maxChars: 24,
      required: true,
      position: "time_block",
      tokenRole: "body_large",
    },
    {
      name: "event_location",
      label: "Event location",
      type: "text",
      minChars: 3,
      maxChars: 60,
      required: true,
      position: "location_block",
      tokenRole: "body_large",
    },
    {
      name: "event_address",
      label: "Street address",
      type: "text",
      minChars: 0,
      maxChars: 80,
      required: false,
      position: "location_block_secondary",
      tokenRole: "body",
    },
    {
      name: "audience_callouts",
      label: "Audience callouts (4-6 bullets)",
      type: "list",
      required: true,
      position: "mid_bullets",
      tokenRole: "body_large",
      listItemMax: 56,
    },
    {
      name: "cta_label",
      label: "Primary CTA",
      type: "text",
      minChars: 3,
      maxChars: 24,
      required: true,
      position: "cta_button",
      tokenRole: "display_small",
    },
    {
      name: "cta_url",
      label: "CTA URL",
      type: "url",
      required: true,
      position: "cta_meta",
    },
    {
      name: "footer_credits",
      label: "Footer (partners / sponsors line)",
      type: "text",
      minChars: 0,
      maxChars: 180,
      required: false,
      position: "footer",
      tokenRole: "caption",
    },
  ],
  imageSlots: [
    {
      name: "hero_photo",
      role: "hero",
      widthPx: 3300,
      heightPx: 2100,
      required: true,
      approvedSource: "program_photo_pool",
    },
    {
      name: "logo_lockup",
      role: "logo",
      required: true,
      approvedSource: "brand_logo_lockups",
    },
    {
      name: "partner_logos",
      role: "logo",
      required: false,
      approvedSource: "partner_logo_library",
    },
  ],
};
