import type { AssetSchema } from "../types";
import { GLOBAL_INHERITED_RULES } from "../brand-rules";

export const flyer8x11Schema: AssetSchema = {
  id: "flyer-8x11",
  displayName: "Flyer 8.5×11 (print + digital PDF)",
  category: "print",
  widthPx: 2550,
  heightPx: 3300,
  outputFormats: ["pdf", "png"],
  inheritedRules: GLOBAL_INHERITED_RULES,
  fields: [
    {
      name: "program_tag",
      label: "Program tag / eyebrow",
      type: "text",
      minChars: 3,
      maxChars: 28,
      required: true,
      position: "top_bar",
      tokenRole: "label_chip",
    },
    {
      name: "headline",
      label: "Headline",
      type: "text",
      minChars: 8,
      maxChars: 45,
      required: true,
      position: "upper_hero",
      tokenRole: "display_xl",
    },
    {
      name: "deck",
      label: "Deck / sub-headline",
      type: "text",
      minChars: 10,
      maxChars: 110,
      required: true,
      position: "below_hero",
      tokenRole: "body_large",
    },
    {
      name: "event_date",
      label: "Event date",
      type: "text",
      minChars: 3,
      maxChars: 28,
      required: true,
      position: "date_block",
      tokenRole: "display_medium",
      example: "AUGUST 1, 2026",
    },
    {
      name: "event_time",
      label: "Event time window",
      type: "text",
      minChars: 3,
      maxChars: 24,
      required: true,
      position: "time_block",
      tokenRole: "body",
      example: "10 AM – 2 PM",
    },
    {
      name: "event_location",
      label: "Event location",
      type: "text",
      minChars: 3,
      maxChars: 60,
      required: true,
      position: "location_block",
      tokenRole: "body",
    },
    {
      name: "event_address",
      label: "Street address",
      type: "text",
      minChars: 0,
      maxChars: 80,
      required: false,
      position: "location_block_secondary",
      tokenRole: "caption",
    },
    {
      name: "audience_callouts",
      label: "Audience callouts (3-5 bullets)",
      type: "list",
      required: true,
      position: "mid_bullets",
      tokenRole: "body",
      listItemMax: 48,
    },
    {
      name: "cta_label",
      label: "Primary CTA",
      type: "text",
      minChars: 3,
      maxChars: 22,
      required: true,
      position: "cta_button",
      tokenRole: "label_chip",
    },
    {
      name: "cta_url",
      label: "CTA URL",
      type: "url",
      required: true,
      position: "cta_meta",
    },
    {
      name: "footer_credits",
      label: "Footer (partners / sponsors line)",
      type: "text",
      minChars: 0,
      maxChars: 140,
      required: false,
      position: "footer",
      tokenRole: "caption",
    },
  ],
  imageSlots: [
    {
      name: "hero_photo",
      role: "hero",
      widthPx: 2550,
      heightPx: 1400,
      required: false,
      approvedSource: "program_photo_pool",
      notes: "Photo panel — text never sits on top of image.",
    },
    {
      name: "logo_lockup",
      role: "logo",
      required: true,
      approvedSource: "brand_logo_lockups",
      notes: "IBTU logo + program sub-brand lockup.",
    },
    {
      name: "partner_logos",
      role: "logo",
      required: false,
      approvedSource: "partner_logo_library",
      notes: "Array — footer strip, monochrome black on white only.",
    },
  ],
};
