import type { AssetSchema } from "../types";
import { GLOBAL_INHERITED_RULES } from "../brand-rules";

export const impactReportPageSchema: AssetSchema = {
  id: "impact-report-page",
  displayName: "Impact Report Page (8.5×11 spread page)",
  category: "print",
  widthPx: 2550,
  heightPx: 3300,
  outputFormats: ["pdf"],
  inheritedRules: GLOBAL_INHERITED_RULES,
  notes:
    "One page inside a multi-page impact report. Page type switches field visibility.",
  fields: [
    {
      name: "page_type",
      label: "Page type",
      type: "enum",
      required: true,
      position: "meta",
      enumValues: [
        "program_spotlight",
        "stat_page",
        "quote_page",
        "case_study",
        "financial_snapshot",
        "board_staff",
        "thank_you",
      ],
    },
    {
      name: "page_title",
      label: "Page title",
      type: "text",
      minChars: 3,
      maxChars: 50,
      required: true,
      position: "title",
      tokenRole: "display_large",
    },
    {
      name: "body",
      label: "Body copy",
      type: "richtext",
      minChars: 80,
      maxChars: 1200,
      required: false,
      position: "body",
      tokenRole: "body",
    },
    {
      name: "hero_stat",
      label: "Hero stat (for stat_page)",
      type: "text",
      minChars: 0,
      maxChars: 10,
      required: false,
      position: "hero_stat",
      tokenRole: "stat_number",
      rules: ["verified_stats_only"],
    },
    {
      name: "hero_stat_label",
      label: "Hero stat label",
      type: "text",
      minChars: 0,
      maxChars: 80,
      required: false,
      position: "hero_stat_caption",
      tokenRole: "body_large",
    },
    {
      name: "pull_quote",
      label: "Pull quote",
      type: "richtext",
      minChars: 0,
      maxChars: 240,
      required: false,
      position: "quote_body",
      tokenRole: "quote",
    },
    {
      name: "quote_attribution",
      label: "Quote attribution",
      type: "text",
      minChars: 0,
      maxChars: 80,
      required: false,
      position: "quote_attribution",
      tokenRole: "caption",
    },
    {
      name: "page_number",
      label: "Page number",
      type: "text",
      minChars: 1,
      maxChars: 5,
      required: true,
      position: "page_footer",
      tokenRole: "caption",
    },
  ],
  imageSlots: [
    {
      name: "hero_photo",
      role: "hero",
      widthPx: 2550,
      heightPx: 1800,
      required: false,
      approvedSource: "program_photo_pool",
    },
  ],
};
