import type { AssetSchema } from "../types";
import { GLOBAL_INHERITED_RULES } from "../brand-rules";

export const jobPostingCardSchema: AssetSchema = {
  id: "job-posting-card",
  displayName: "Job Posting Card",
  category: "web",
  fluid: true,
  outputFormats: ["jsx"],
  inheritedRules: GLOBAL_INHERITED_RULES,
  fields: [
    {
      name: "title",
      label: "Role title",
      type: "text",
      minChars: 4,
      maxChars: 70,
      required: true,
      position: "title",
      tokenRole: "display_small",
    },
    {
      name: "type",
      label: "Employment type",
      type: "enum",
      required: true,
      position: "type_chip",
      enumValues: ["full_time", "part_time", "contract", "internship", "volunteer_lead"],
    },
    {
      name: "department",
      label: "Department",
      type: "enum",
      required: true,
      position: "dept_chip",
      enumValues: [
        "programs",
        "development",
        "marketing",
        "operations",
        "finance",
        "volunteer",
        "brand_creative",
      ],
    },
    {
      name: "location",
      label: "Location",
      type: "text",
      minChars: 3,
      maxChars: 40,
      required: true,
      position: "location",
      tokenRole: "caption",
    },
    {
      name: "description",
      label: "Short description",
      type: "richtext",
      minChars: 80,
      maxChars: 600,
      required: true,
      position: "body",
      tokenRole: "body",
    },
    {
      name: "how_to_apply",
      label: "How to apply",
      type: "richtext",
      minChars: 40,
      maxChars: 280,
      required: true,
      position: "apply",
      tokenRole: "body_small",
    },
    {
      name: "active",
      label: "Active / open",
      type: "enum",
      required: true,
      position: "meta",
      enumValues: ["open", "closed", "talent_pool"],
    },
    {
      name: "date_posted",
      label: "Date posted",
      type: "date",
      required: true,
      position: "meta",
    },
  ],
  imageSlots: [],
};
