import type { AssetSchema } from "../types";
import { GLOBAL_INHERITED_RULES } from "../brand-rules";

export const newsArticleSchema: AssetSchema = {
  id: "news-article",
  displayName: "News / Press Article",
  category: "web",
  fluid: true,
  outputFormats: ["jsx"],
  inheritedRules: GLOBAL_INHERITED_RULES,
  notes: "Drives both internal articles and external press links — when externalUrl is set, card links out.",
  fields: [
    {
      name: "title",
      label: "Article title",
      type: "text",
      minChars: 8,
      maxChars: 110,
      required: true,
      position: "title",
      tokenRole: "display_medium",
    },
    {
      name: "category",
      label: "Category",
      type: "enum",
      required: true,
      position: "eyebrow",
      enumValues: ["Press Mention", "Announcement", "Impact Story", "Partnership", "Award"],
    },
    {
      name: "published_at",
      label: "Published date",
      type: "date",
      required: true,
      position: "date",
    },
    {
      name: "deck",
      label: "Deck (1-2 sentence teaser)",
      type: "text",
      minChars: 40,
      maxChars: 240,
      required: true,
      position: "deck",
      tokenRole: "body_large",
    },
    {
      name: "body",
      label: "Full body (for internal articles)",
      type: "richtext",
      minChars: 0,
      maxChars: 8000,
      required: false,
      position: "body",
      tokenRole: "body",
    },
    {
      name: "external_url",
      label: "External URL (for press mentions)",
      type: "url",
      required: false,
      position: "external_link",
    },
    {
      name: "source_publication",
      label: "Source publication (for press mentions)",
      type: "text",
      minChars: 0,
      maxChars: 60,
      required: false,
      position: "source_chip",
      tokenRole: "caption",
    },
    {
      name: "featured",
      label: "Featured on news index",
      type: "enum",
      required: true,
      position: "meta",
      enumValues: ["yes", "no"],
    },
  ],
  imageSlots: [
    {
      name: "hero_image",
      role: "hero",
      aspectRatio: "16:9",
      required: true,
      approvedSource: "program_photo_pool",
    },
  ],
};
