import type { AssetSchema } from "../types";
import { GLOBAL_INHERITED_RULES } from "../brand-rules";

export const oneSheetSchema: AssetSchema = {
  id: "one-sheet",
  displayName: "Program One-Sheet (8.5×11, front + back)",
  category: "print",
  widthPx: 2550,
  heightPx: 3300,
  outputFormats: ["pdf"],
  inheritedRules: GLOBAL_INHERITED_RULES,
  notes: "Front = program story + hero photo + stats. Back = tiers/CTA/partners.",
  fields: [
    {
      name: "program_name",
      label: "Program name",
      type: "text",
      minChars: 3,
      maxChars: 40,
      required: true,
      position: "front_eyebrow",
      tokenRole: "label_chip",
    },
    {
      name: "front_headline",
      label: "Front headline",
      type: "text",
      minChars: 8,
      maxChars: 60,
      required: true,
      position: "front_hero",
      tokenRole: "display_xl",
    },
    {
      name: "front_deck",
      label: "Front deck (1-2 sentences)",
      type: "richtext",
      minChars: 40,
      maxChars: 260,
      required: true,
      position: "front_body",
      tokenRole: "body_large",
    },
    {
      name: "impact_stats",
      label: "Impact stats (3-5 big numbers with labels)",
      type: "list",
      required: true,
      position: "front_stat_strip",
      listItemMax: 60,
      rules: ["verified_stats_only"],
    },
    {
      name: "back_headline",
      label: "Back headline",
      type: "text",
      minChars: 8,
      maxChars: 50,
      required: true,
      position: "back_hero",
      tokenRole: "display_large",
    },
    {
      name: "back_intro",
      label: "Back intro copy",
      type: "richtext",
      minChars: 40,
      maxChars: 280,
      required: true,
      position: "back_intro",
      tokenRole: "body",
    },
    {
      name: "sponsor_tiers_summary",
      label: "Sponsor tier summary (name + price + key deliverable, per tier)",
      type: "list",
      required: true,
      position: "back_tier_list",
      tokenRole: "body",
      listItemMax: 120,
    },
    {
      name: "cta_label",
      label: "CTA",
      type: "text",
      minChars: 3,
      maxChars: 28,
      required: true,
      position: "back_cta",
      tokenRole: "display_small",
    },
    {
      name: "cta_url",
      label: "CTA URL",
      type: "url",
      required: true,
      position: "back_cta_meta",
    },
    {
      name: "contact_info",
      label: "Contact block (email + phone)",
      type: "text",
      minChars: 10,
      maxChars: 120,
      required: true,
      position: "back_footer",
      tokenRole: "body_small",
    },
  ],
  imageSlots: [
    {
      name: "front_hero_photo",
      role: "hero",
      widthPx: 2550,
      heightPx: 1500,
      required: true,
      approvedSource: "program_photo_pool",
    },
    {
      name: "back_proof_photo",
      role: "proof_photo",
      widthPx: 2550,
      heightPx: 900,
      required: false,
      approvedSource: "program_photo_pool",
    },
    {
      name: "logo_lockup",
      role: "logo",
      required: true,
      approvedSource: "brand_logo_lockups",
    },
    {
      name: "partner_logos",
      role: "logo",
      required: false,
      approvedSource: "partner_logo_library",
    },
  ],
};
