import type { AssetSchema } from "../types";
import { GLOBAL_INHERITED_RULES } from "../brand-rules";

export const programLandingHeroSchema: AssetSchema = {
  id: "program-landing-hero",
  displayName: "Program Landing Hero Section",
  category: "web",
  fluid: true,
  outputFormats: ["jsx"],
  inheritedRules: GLOBAL_INHERITED_RULES,
  fields: [
    {
      name: "program_eyebrow",
      label: "Program eyebrow",
      type: "text",
      minChars: 3,
      maxChars: 28,
      required: true,
      position: "eyebrow",
      tokenRole: "label_chip",
    },
    {
      name: "hero_headline",
      label: "Hero headline (sacred phrase)",
      type: "text",
      minChars: 10,
      maxChars: 80,
      required: true,
      position: "hero_title",
      tokenRole: "display_xl",
      rules: ["sacred_phrases_verbatim"],
    },
    {
      name: "hero_tagline",
      label: "Hero tagline",
      type: "richtext",
      minChars: 30,
      maxChars: 220,
      required: true,
      position: "hero_tagline",
      tokenRole: "body_large",
    },
    {
      name: "proof_stats",
      label: "Proof stats (up to 4)",
      type: "list",
      required: true,
      position: "stat_strip",
      tokenRole: "stat_number",
      listItemMax: 60,
      rules: ["verified_stats_only"],
    },
    {
      name: "primary_cta_label",
      label: "Primary CTA",
      type: "text",
      minChars: 3,
      maxChars: 22,
      required: true,
      position: "primary_cta",
      tokenRole: "label_chip",
    },
    {
      name: "secondary_cta_label",
      label: "Secondary CTA",
      type: "text",
      minChars: 0,
      maxChars: 22,
      required: false,
      position: "secondary_cta",
      tokenRole: "label_chip",
    },
  ],
  imageSlots: [
    {
      name: "hero_video_or_image",
      role: "hero",
      required: true,
      approvedSource: "program_hero_media",
      notes: "Video or still. Lives in a dedicated panel — never behind text.",
    },
  ],
};
