import type { AssetSchema } from "../types";
import { GLOBAL_INHERITED_RULES } from "../brand-rules";

export const socialSquareSchema: AssetSchema = {
  id: "social-square",
  displayName: "Social Square (1080×1080)",
  category: "social",
  widthPx: 1080,
  heightPx: 1080,
  outputFormats: ["png", "jpg"],
  inheritedRules: GLOBAL_INHERITED_RULES,
  fields: [
    {
      name: "eyebrow",
      label: "Eyebrow (program tag)",
      type: "text",
      minChars: 3,
      maxChars: 22,
      required: true,
      position: "top_left",
      tokenRole: "label_chip",
      example: "BACK 2 SCHOOL 2026",
    },
    {
      name: "headline",
      label: "Headline",
      type: "text",
      minChars: 10,
      maxChars: 55,
      required: true,
      position: "center_large",
      tokenRole: "display_large",
      example: "Every child deserves to start the year with dignity.",
    },
    {
      name: "subhead",
      label: "Subhead",
      type: "text",
      minChars: 0,
      maxChars: 80,
      required: false,
      position: "center_below_headline",
      tokenRole: "body",
    },
    {
      name: "date_location",
      label: "Date + location chip",
      type: "text",
      minChars: 0,
      maxChars: 40,
      required: false,
      position: "bottom_left",
      tokenRole: "label_chip",
      example: "AUG 1 · BHC PLAZA",
    },
    {
      name: "cta_label",
      label: "CTA label",
      type: "text",
      minChars: 3,
      maxChars: 22,
      required: true,
      position: "bottom_right",
      tokenRole: "label_chip",
      example: "RSVP AT IBTU.LA",
    },
  ],
  imageSlots: [
    {
      name: "proof_image",
      role: "proof_photo",
      widthPx: 1080,
      heightPx: 540,
      required: false,
      approvedSource: "program_photo_pool",
      notes: "Optional — omit for type-only design.",
    },
  ],
};
