import type { AssetSchema } from "../types";
import { GLOBAL_INHERITED_RULES } from "../brand-rules";

export const socialStorySchema: AssetSchema = {
  id: "social-story",
  displayName: "Social Story (1080×1920)",
  category: "social",
  widthPx: 1080,
  heightPx: 1920,
  outputFormats: ["png", "jpg"],
  inheritedRules: GLOBAL_INHERITED_RULES,
  fields: [
    {
      name: "eyebrow",
      label: "Eyebrow (program tag)",
      type: "text",
      minChars: 3,
      maxChars: 22,
      required: true,
      position: "top_center",
      tokenRole: "label_chip",
    },
    {
      name: "headline",
      label: "Headline",
      type: "text",
      minChars: 10,
      maxChars: 40,
      required: true,
      position: "upper_third",
      tokenRole: "display_xl",
    },
    {
      name: "subhead",
      label: "Subhead",
      type: "text",
      minChars: 0,
      maxChars: 90,
      required: false,
      position: "middle_third",
      tokenRole: "body_large",
    },
    {
      name: "stat_number",
      label: "Hero stat",
      type: "text",
      minChars: 0,
      maxChars: 10,
      required: false,
      position: "middle_stat",
      tokenRole: "stat_number",
      example: "18,550+",
      rules: ["verified_stats_only"],
    },
    {
      name: "stat_label",
      label: "Stat label",
      type: "text",
      minChars: 0,
      maxChars: 40,
      required: false,
      position: "middle_stat_caption",
      tokenRole: "caption",
    },
    {
      name: "cta_label",
      label: "CTA label",
      type: "text",
      minChars: 3,
      maxChars: 22,
      required: true,
      position: "bottom_third",
      tokenRole: "label_chip",
    },
    {
      name: "swipe_up_url",
      label: "Swipe-up URL",
      type: "url",
      required: true,
      position: "meta",
      example: "https://ibtu.la/back2school",
    },
  ],
  imageSlots: [
    {
      name: "background_photo",
      role: "background",
      widthPx: 1080,
      heightPx: 1920,
      required: false,
      approvedSource: "program_photo_pool",
      notes: "If used, headline sits on solid color panel over photo — no text directly on photo.",
    },
  ],
};
