import type { AssetSchema } from "../types";
import { GLOBAL_INHERITED_RULES } from "../brand-rules";

export const socialCarouselSlideSchema: AssetSchema = {
  id: "social-carousel-slide",
  displayName: "Social Carousel Slide (1080×1350)",
  category: "social",
  widthPx: 1080,
  heightPx: 1350,
  outputFormats: ["png", "jpg"],
  inheritedRules: GLOBAL_INHERITED_RULES,
  notes:
    "Each slide is a single unit in a multi-slide carousel (typically 4-7 slides). Slide 1 = cover, Slide N = CTA. Interior slides populate this schema.",
  fields: [
    {
      name: "slide_number",
      label: "Slide number (of total)",
      type: "text",
      minChars: 3,
      maxChars: 8,
      required: true,
      position: "top_right",
      tokenRole: "label_chip",
      example: "02 / 05",
    },
    {
      name: "kicker",
      label: "Slide kicker",
      type: "text",
      minChars: 3,
      maxChars: 28,
      required: true,
      position: "top_left",
      tokenRole: "label_chip",
      example: "BY THE NUMBERS",
    },
    {
      name: "stat_number",
      label: "Big number",
      type: "text",
      minChars: 1,
      maxChars: 10,
      required: false,
      position: "center_stat",
      tokenRole: "stat_number",
      rules: ["verified_stats_only"],
    },
    {
      name: "stat_label",
      label: "Stat label",
      type: "text",
      minChars: 3,
      maxChars: 60,
      required: false,
      position: "center_stat_caption",
      tokenRole: "body",
    },
    {
      name: "body_copy",
      label: "Body copy (if no stat)",
      type: "richtext",
      minChars: 0,
      maxChars: 180,
      required: false,
      position: "center_body",
      tokenRole: "body_large",
    },
    {
      name: "footer_tag",
      label: "Footer tag (program / handle)",
      type: "text",
      minChars: 3,
      maxChars: 24,
      required: true,
      position: "bottom_center",
      tokenRole: "caption",
      example: "@ITSBIGGERTHANUS",
    },
  ],
  imageSlots: [
    {
      name: "supporting_image",
      role: "proof_photo",
      widthPx: 1080,
      heightPx: 600,
      required: false,
      approvedSource: "program_photo_pool",
    },
  ],
};
