import type { AssetSchema } from "../types";
import { GLOBAL_INHERITED_RULES } from "../brand-rules";

export const sponsorDeckSlideSchema: AssetSchema = {
  id: "sponsor-deck-slide",
  displayName: "Sponsor Deck Slide (1920×1080)",
  category: "deck",
  widthPx: 1920,
  heightPx: 1080,
  outputFormats: ["pdf", "png"],
  inheritedRules: GLOBAL_INHERITED_RULES,
  notes:
    "One slide in a 10-20 slide sponsor deck. Slide type switches field visibility (tier table, stats proof, case study, CTA).",
  fields: [
    {
      name: "slide_type",
      label: "Slide type",
      type: "enum",
      required: true,
      position: "meta",
      enumValues: [
        "cover",
        "program_intro",
        "audience_impact",
        "stats_proof",
        "case_study",
        "tier_table",
        "deliverables_matrix",
        "past_partners",
        "closing_cta",
      ],
    },
    {
      name: "slide_title",
      label: "Slide title",
      type: "text",
      minChars: 4,
      maxChars: 60,
      required: true,
      position: "title",
      tokenRole: "display_large",
    },
    {
      name: "slide_deck",
      label: "Subhead / deck",
      type: "text",
      minChars: 0,
      maxChars: 160,
      required: false,
      position: "subtitle",
      tokenRole: "body_large",
    },
    {
      name: "body_columns",
      label: "Body (1-3 columns of content)",
      type: "richtext",
      minChars: 0,
      maxChars: 800,
      required: false,
      position: "body",
      tokenRole: "body",
    },
    {
      name: "stat_set",
      label: "Stat set (up to 4 big numbers)",
      type: "list",
      required: false,
      position: "stat_strip",
      tokenRole: "stat_number",
      listItemMax: 80,
      rules: ["verified_stats_only"],
    },
    {
      name: "tier_names",
      label: "Tier names (for tier_table slide)",
      type: "list",
      required: false,
      position: "tier_header",
      tokenRole: "display_small",
      listItemMax: 28,
    },
    {
      name: "tier_prices",
      label: "Tier prices",
      type: "list",
      required: false,
      position: "tier_price",
      tokenRole: "stat_number",
      listItemMax: 16,
    },
    {
      name: "tier_deliverables",
      label: "Deliverables per tier",
      type: "list",
      required: false,
      position: "tier_cells",
      tokenRole: "body_small",
      listItemMax: 120,
    },
    {
      name: "footer_page_number",
      label: "Footer page x/y",
      type: "text",
      minChars: 3,
      maxChars: 10,
      required: true,
      position: "footer_right",
      tokenRole: "caption",
    },
  ],
  imageSlots: [
    {
      name: "slide_hero",
      role: "hero",
      widthPx: 1920,
      heightPx: 640,
      required: false,
      approvedSource: "program_photo_pool",
    },
    {
      name: "logo_lockup",
      role: "logo",
      required: true,
      approvedSource: "brand_logo_lockups",
      notes: "Bottom-left.",
    },
  ],
};
