import type { AssetSchema } from "../types";
import { GLOBAL_INHERITED_RULES } from "../brand-rules";

export const vendorPortalStepSchema: AssetSchema = {
  id: "vendor-portal-step",
  displayName: "Vendor Portal Step (Zapier Interface page)",
  category: "portal",
  fluid: true,
  outputFormats: ["jsx"],
  inheritedRules: GLOBAL_INHERITED_RULES,
  notes:
    "One of 5 steps in the vendor intake wizard at vendors.ibtu.la. Drives what Zapier Interfaces renders per step.",
  fields: [
    {
      name: "step_number",
      label: "Step number",
      type: "number",
      required: true,
      position: "progress_bar",
    },
    {
      name: "step_of_total",
      label: "Total steps",
      type: "number",
      required: true,
      position: "progress_bar",
    },
    {
      name: "step_label",
      label: "Step label",
      type: "text",
      minChars: 3,
      maxChars: 28,
      required: true,
      position: "progress_label",
      tokenRole: "label_chip",
      example: "PROFILE",
    },
    {
      name: "step_headline",
      label: "Step headline",
      type: "text",
      minChars: 6,
      maxChars: 60,
      required: true,
      position: "title",
      tokenRole: "display_medium",
    },
    {
      name: "step_body",
      label: "Step body (context for vendor)",
      type: "richtext",
      minChars: 40,
      maxChars: 320,
      required: true,
      position: "body",
      tokenRole: "body",
    },
    {
      name: "help_note",
      label: "Help note / tip",
      type: "richtext",
      minChars: 0,
      maxChars: 240,
      required: false,
      position: "help_panel",
      tokenRole: "body_small",
    },
    {
      name: "next_cta_label",
      label: "Next button label",
      type: "text",
      minChars: 3,
      maxChars: 22,
      required: true,
      position: "next_button",
      tokenRole: "label_chip",
    },
  ],
  imageSlots: [],
};
